# here set the path to your arduino installation.
ARDU=/home/kacianka/.arduino15
# these flags come directly from the IDE compile
# we can change them, but we need good reason to:) 
CC = ${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ 
CFLAGS=-mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC
INCLUDES = -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010
# this part I do not fully understand
LIBS = -L.  -Os -Wl,--gc-sections -save-temps -T${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010/linker_scripts/gcc/flash_with_bootloader.ld -Wl,-Map,main.map --specs=nano.specs --specs=nosys.specs -mcpu=cortex-m0plus -mthumb -Wl,--cref -Wl,--check-sections -Wl,--gc-sections -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-section-align -o main.elf main.o variant.cpp.o -Wl,--start-group -L${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Lib/GCC/ -larm_cortexM0l_math -lm ./core/core.a -Wl,--end-group

SRC = main.cpp

# the compilation now is a bit tricky it goes a bit like this:
# 1) compile the core arduino library
# 2) compile the main.cpp
# 3) compile the variant, which is as far as I know just a library for the
# specific board
# 4) link everything together
# 5) create the binary 

all: compile

compile: main.bin

main.o: main.cpp
	${CC} ${CFLAGS} ${INCLUDES} ${SRC} -o main.o

variant.cpp.o:
	${CC} ${CFLAGS} ${INCLUDES} ${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010/variant.cpp -o variant.cpp.o 

link: variant.cpp.o core/core.a
	${CC} ${LIBS}

main.bin: main.o link 
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-objcopy -O binary main.elf main.bin
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-objcopy -O ihex -R .eeprom main.elf main.hex
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-size -A main.elf
# Very important: to upload a binary we first need to push the reset button
# twice!
# Otherwise the upload will fail. 
#https://forum.arduino.cc/t/no-device-found-on-ttyacm0-both-with-arduino-ide-2-0-3-and-arduino-iot-cloud/1062050
upload: main.bin
	${ARDU}/packages/arduino/tools/bossac/1.7.0-arduino3/bossac -i -d --port=/dev/ttyACM0 -U true -i -e -w -v main.bin -R


	
clean:
	rm -f *.o
	rm -f *.d
	rm -f *.map
	rm -f *.hex
	rm -f *.bin
	rm -f *.elf
	rm -rf core

# This part is more or less copy pasted from the IDE
# there might be a nicer way of doing it, but let's cross that bridge when we
# get there :) 
core/core.a:
	mkdir core
	mkdir core/api
	mkdir core/USB
	mkdir core/compact
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/Reset.cpp -o ./core/Reset.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/CanMsgRingbuffer.cpp -o ./core/api/CanMsgRingbuffer.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/Tone.cpp -o ./core/Tone.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/USB/samd21_host.c -o ./core/USB/samd21_host.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/USB/CDC.cpp -o ./core/USB/CDC.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/WMath.cpp -o ./core/WMath.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/CanMsg.cpp -o ./core/api/CanMsg.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/SERCOM.cpp -o ./core/SERCOM.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/Uart.cpp -o ./core/Uart.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/abi.cpp -o ./core/abi.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/WInterrupts.c -o ./core/WInterrupts.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/USB/USBCore.cpp -o ./core/USB/USBCore.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/Common.cpp -o ./core/api/Common.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/IPAddress.cpp -o ./core/api/IPAddress.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/PluggableUSB.cpp -o ./core/api/PluggableUSB.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/Print.cpp -o ./core/api/Print.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/Stream.cpp -o ./core/api/Stream.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/String.cpp -o ./core/api/String.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/compact/dtostrf.c -o ./core/compact/dtostrf.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/cortex_handlers.c -o ./core/cortex_handlers.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/delay.c -o ./core/delay.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/hooks.c -o ./core/hooks.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/itoa.c -o ./core/itoa.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/main.cpp -o ./core/main.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/new.cpp -o ./core/new.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/pulse.c -o ./core/pulse.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/startup.c -o ./core/startup.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -x assembler-with-cpp -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/pulse_asm.S -o ./core/pulse_asm.S.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/wiring.c -o ./core/wiring.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/wiring_analog.c -o ./core/wiring_analog.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/wiring_private.c -o ./core/wiring_private.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/wiring_digital.c -o ./core/wiring_digital.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino MKR WiFi 1010\"" -DUSE_BQ24195L_PMIC -I${ARDU}/packages/arduino/tools/CMSIS/4.5.0/CMSIS/Include/ -I${ARDU}/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/api/deprecated-avr-comp -I${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino -I${ARDU}/packages/arduino/hardware/samd/1.8.14/variants/mkrwifi1010 ${ARDU}/packages/arduino/hardware/samd/1.8.14/cores/arduino/wiring_shift.c -o ./core/wiring_shift.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/Reset.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/SERCOM.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/Tone.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/USB/CDC.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/USB/USBCore.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/USB/samd21_host.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/Uart.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/WInterrupts.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/WMath.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/abi.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/CanMsg.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/CanMsgRingbuffer.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/Common.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/IPAddress.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/PluggableUSB.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/Print.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/Stream.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/api/String.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/compact/dtostrf.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/cortex_handlers.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/delay.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/hooks.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/itoa.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/main.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/new.cpp.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/pulse.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/pulse_asm.S.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/startup.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/wiring.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/wiring_analog.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/wiring_digital.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/wiring_private.c.o
	${ARDU}/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-ar rcs ./core/core.a ./core/wiring_shift.c.o

